# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 262f55da0a2d5ef7a342d87520fb7e87b851ef106e3ec688f3e1713cb4e87f866f6d8cdf8a7ca5acbc90287236f5bd2d5432394e63869c4a882c1d7f0dad8990

test:
  secret_key_base: 94466335af8ce9bdbe526597e216f5bb56c9483c6fd2fe6574e774b8c37ccf06f6d74ad8debfa10873375cf71029ee712ef08de9a672dd19427af722b3af47df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
